import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex items-center gap-6 px-6 py-4 bg-gray-900 text-white">
          <Link href='/' className="hover:text-gray-300 font-semibold">Home</Link>
          <Link href="/books" className="hover:text-gray-300 font-semibold">Books</Link>
          <Link href="/add-book" className="hover:text-gray-300 font-semibold">Add a new book</Link>
        </nav>
        <main className="max-w-5xl mx-auto px-6 py-8">
          {children}
        </main>
      </body>
    </html>
  );
}
