import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  Show, //Show,SignIn&UpButton & UserButton are all Clerk components
  SignInButton, // that we can use on the page
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            {/* Code added start*/}
        <ClerkProvider>
          <header className="flex justify-end items-center p-4 gap-4 h-16"> {/* Tailwind css styling for the header*/}
            <Show when="signed-out"> {/* Clerk's <Show/> will only its content when we meet it's condition*/}
              <SignInButton /> {/* Show a sign in/ sign up button or if signed in the UserButton */}
              <SignUpButton>
                <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
          {children} {/* The page we are on */}
        </ClerkProvider>
            {/* Code added end */}
      </body>
    </html>
  );
}
