import { Coral_Pixels, Sour_Gummy, Honk } from "next/font/google";
import "./globals.css";

// Coral_Pixel takes an object as an arg, with our settings
export const coral_pixel = Coral_Pixels({
  weight: '400',
  subsets: ['latin']
})

const sour_gummy = Sour_Gummy()

const honk = Honk({
  variable: '--font-honk'
})

console.log(coral_pixel)


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* I need to give the variable to my app so it's avialbable */}
      <body
        className={`${sour_gummy.className} ${honk.variable} antialiased h-dvh` }
      >
        {children}
      </body>
    </html>
  );
}
